server:
  port: 8181

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jpa?serverTimezone=Asia/Seoul
    username: spring
    password: spring
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa: # mysql에서 jpa라는 이름을 가진 데이터베이스에 만드는 것
    # show-sql: true # 자동 생성된 쿼리를 보여주는 옵션
    # 방언 설정 -> 각 DB에 맞는 쿼리를 설정
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create # 자동 DDL 설정 옵션 -> create로 설정하면 클래스 모양대로 테이블 자동 생성.
   # properties:
    #  hibernate:
     #   format_sql: true # sql을 줄바꿈해서 이쁘게 출력
    database: mysql # DB 계열 설정


logging.level:
  org.hibernate.SQL: debug